const countryList = {
    usa: "USA",
    canada: "Canada",
    "united kingdom": "United Kingdom",
    germany: "Germany",
    france: "France",
    spain: "Spain",
    italy: "Italy",
    sweden: "Sweden",
    greece: "Greece",
    portugal: "Portugal",
    netherlands: "Netherlands",
    belgium: "Belgium",
    russia: "Russia",
    ukraine: "Ukraine",
    poland: "Poland",
    israel: "Israel",
    turkey: "Turkey",
    australia: "Australia",
    malaysia: "Malaysia",
    thailand: "Thailand",
    "south korea": "South Korea",
    japan: "Japan",
    philippines: "Philippines",
    singapore: "Singapore",
    china: "China",
    "hong kong": "Hong Kong",
    taiwan: "Taiwan",
    india: "India",
    pakistan: "Pakistan",
    iran: "Iran",
    indonesia: "Indonesia",
    azerbaijan: "Azerbaijan",
    kazakhstan: "Kazakhstan",
    uae: "UAE",
    mexico: "Mexico",
    brazil: "Brazil",
    argentina: "Argentina",
    chile: "Chile",
    peru: "Peru",
    ecuador: "Ecuador",
    colombia: "Colombia",
    "south africa": "South Africa",
    egypt: "Egypt",
    "saudi arabia": "Saudi Arabia",
    denmark: "Denmark",
    angola: "Angola",
    cameroon: "Cameroon",
    "central african republic": "Central African Republic",
    chad: "Chad",
    benin: "Benin",
    ethiopia: "Ethiopia",
    djibouti: "Djibouti",
    gambia: "Gambia",
    ghana: "Ghana",
    "côte d'ivoire": "Côte d'Ivoire",
    kenya: "Kenya",
    liberia: "Liberia",
    madagascar: "Madagascar",
    mali: "Mali",
    mauritania: "Mauritania",
    mauritius: "Mauritius",
    morocco: "Morocco",
    mozambique: "Mozambique",
    nigeria: "Nigeria",
    senegal: "Senegal",
    seychelles: "Seychelles",
    zimbabwe: "Zimbabwe",
    "south sudan": "South Sudan",
    sudan: "Sudan",
    togo: "Togo",
    tunisia: "Tunisia",
    uganda: "Uganda",
    zambia: "Zambia",
    afghanistan: "Afghanistan",
    bahrain: "Bahrain",
    bangladesh: "Bangladesh",
    armenia: "Armenia",
    bhutan: "Bhutan",
    myanmar: "Myanmar",
    cambodia: "Cambodia",
    georgia: "Georgia",
    iraq: "Iraq",
    jordan: "Jordan",
    lebanon: "Lebanon",
    maldives: "Maldives",
    mongolia: "Mongolia",
    oman: "Oman",
    qatar: "Qatar",
    vietnam: "Vietnam",
    turkmenistan: "Turkmenistan",
    uzbekistan: "Uzbekistan",
    yemen: "Yemen",
    albania: "Albania",
    andorra: "Andorra",
    austria: "Austria",
    "bosnia and herzegovina": "Bosnia and Herzegovina",
    bulgaria: "Bulgaria",
    belarus: "Belarus",
    croatia: "Croatia",
    cyprus: "Cyprus",
    "czech republic": "Czech Republic",
    estonia: "Estonia",
    finland: "Finland",
    hungary: "Hungary",
    iceland: "Iceland",
    ireland: "Ireland",
    latvia: "Latvia",
    liechtenstein: "Liechtenstein",
    lithuania: "Lithuania",
    luxembourg: "Luxembourg",
    malta: "Malta",
    monaco: "Monaco",
    moldova: "Moldova",
    montenegro: "Montenegro",
    norway: "Norway",
    romania: "Romania",
    serbia: "Serbia",
    slovakia: "Slovakia",
    slovenia: "Slovenia",
    switzerland: "Switzerland",
    macedonia: "Macedonia",
    bahamas: "Bahamas",
    belize: "Belize",
    "british virgin islands": "British Virgin Islands",
    "costa rica": "Costa Rica",
    cuba: "Cuba",
    dominica: "Dominica",
    haiti: "Haiti",
    honduras: "Honduras",
    jamaica: "Jamaica",
    aruba: "Aruba",
    panama: "Panama",
    "puerto rico": "Puerto Rico",
    "trinidad and tobago": "Trinidad and Tobago",
    fiji: "Fiji",
    "new zealand": "New Zealand",
    bolivia: "Bolivia",
    paraguay: "Paraguay",
    uruguay: "Uruguay",
    venezuela: "Venezuela",
  };
export default countryList  